roles:
  - src: avanov.pyenv
    version: 1.1.0
collections:
  - name: junipernetworks.junos
    version: 1.2.1
  - name: paloaltonetworks.panos
    version: 1.1.0
  - name: cisco.meraki
    version: 1.4.0
  - name: arista.eos
    version: 1.0.3
  - name: cisco.nxos
    version: 1.3.1
