---
- name: eos - aaa
  block:
    - name: eos - get config
      arista.eos.eos_command:
        commands: 'show running-config all | exclude \.\*'
      register: output
      when: _eos_config is not defined

    - name: eos - save config as fact
      set_fact:
        _eos_config: "{{ output.stdout[0] }}"
      no_log: "{{ no_log | default(true) }}"
      when: _eos_config is not defined

    - name: eos - configure radius server
      arista.eos.eos_config:
        src: arista/radius.j2
        defaults: yes
        save_when: changed
        config: "{{ _eos_config | default(omit) }}"
      with_items: "{{ aaa }}"
      when: aaa is defined

    - name: eos - configure aaa
      arista.eos.eos_config:
        src: arista/aaa.j2
        defaults: yes
        save_when: changed
        config: "{{ _eos_config | default(omit) }}"
      with_items: "{{ aaa }}"
      when: aaa is defined
  when: ansible_network_os == 'arista.eos.eos'

- name: nxos - aaa
  block:
    - name: nxos - aaa server
      cisco.nxos.nxos_config:
        src: cisco/aaa.j2
        diff_against: running
        save_when: changed
        defaults: yes
      with_items: "{{ aaa }}"
      when: aaa is defined
  when: ansible_network_os == 'cisco.nxos.nxos'
...
