---
- name: junos - hostname
  block:
    - name: configure hostname
      junipernetworks.junos.junos_config:
        update: "merge"
        src: "junos/hostname.j2"
        src_format: "set"
  when: ansible_network_os == 'junipernetworks.junos.junos'

- name: eos - hostname
  block:
    - name: get eos config
      arista.eos.eos_command:
        commands: 'show running-config all | exclude \.\*'
      register: output
      when: _eos_config is not defined

    - name: save eos config as fact
      set_fact:
        _eos_config: "{{ output.stdout[0] }}"
      no_log: "{{ no_log | default(true) }}"
      when: _eos_config is not defined

    - name: set hostname
      arista.eos.eos_config:
        src: arista/hostname.j2
        defaults: true
        save_when: changed
        config: "{{ _eos_config | default(omit) }}"
      when: hostname is defined
  when: ansible_network_os == 'arista.eos.eos'

- name: nxos - hostname
  block:
    - name: nxos - configure hostname
      cisco.nxos.nxos_config:
        src: cisco/hostname.j2
        diff_against: running
        save_when: changed
      when: hostname is defined
  when: ansible_network_os == 'cisco.nxos.nxos'
...
