---
- name: junos - logging
  block:
    - name: junos - configure logging
      junipernetworks.junos.junos_config:
        update: "merge"
        src: "junos/logging.j2"
        src_format: "set"
      when: logging is defined
  when: ansible_network_os == 'junipernetworks.junos.junos'

- name: eos - logging
  block:
    - name: eos - get config
      arista.eos.eos_command:
        commands: 'show running-config all | exclude \.\*'
      register: output
      no_log: "{{ no_log | default(true) }}"
      when: _eos_config is not defined

    - name: eos - save config as fact
      set_fact:
        _eos_config: "{{ output.stdout[0] }}"
      no_log: "{{ no_log | default(true) }}"
      when: _eos_config is not defined

    - name: eos - configure logging
      arista.eos.eos_config:
        src: arista/logging.j2
        defaults: yes
        save_when: changed
        config: "{{ _eos_config | default(omit) }}"
      with_items: "{{ logging }}"
      no_log: false
      when: logging is defined
  when: ansible_network_os == 'arista.eos.eos'

- name: nxos - logging
  block:
    - name: nxos - configure logging
      cisco.nxos.nxos_config:
        src: cisco/logging.j2
        diff_against: running
        save_when: changed
      with_items: "{{ logging }}"
      when: logging is defined
  when: ansible_network_os == 'cisco.nxos.nxos'
...
