---
- name: eos - vlan
  block:
    - name: eos - get config
      arista.eos.eos_command:
        commands: 'show running-config all | exclude \.\*'
      register: output
      no_log: "{{ no_log | default(true) }}"
      when: _eos_config is not defined

    - name: eos - save config as fact
      set_fact:
        _eos_config: "{{ output.stdout[0] }}"
      no_log: "{{ no_log | default(true) }}"
      when: _eos_config is not define

    - name: eos - build vlans
      arista.eos.eos_config:
        src: arista/vlan.j2
        defaults: yes
        config: "{{ _eos_config | default(omit) }}"
        after: write memory
      with_items: "{{ vlans }}"
      when: vlans is defined
  when: ansible_network_os == 'arista.eos.eos'

- name: nxos - vlan
  block:
    - name: nxos - configure vlans
      cisco.nxos.nxos_config:
        src: cisco/vlan.j2
        diff_against: running
        save_when: changed
      with_items: "{{ vlans }}"
      when: vlans is defined
  when: ansible_network_os == 'cisco.nxos.nxos'
...
